"""
Exercise 3 — Answers
====================
Fill this in after completing the three Rasa conversations.

CALM vs Old Rasa — what changed
---------------------------------
The old open-source Rasa approach used:
  - nlu.yml: intent training examples
  - rules.yml: explicit dialogue rules
  - FormValidationAction: Python class to parse slot values

Rasa Pro CALM uses:
  - flows.yml: natural language descriptions of what each flow does
  - from_llm slots: the LLM extracts values from conversation
  - ONE custom action: ActionValidateBooking for the business rules

The conversation is the same from the manager's perspective.
The machinery underneath is completely different.

CONVERSATION SCRIPTS
---------------------
Conversation 1 (happy path):
  You:    calling to confirm a booking
  Agent:  [asks guest count]
  You:    160 guests
  Agent:  [asks vegan count]
  You:    about 50 need vegan
  Agent:  [asks deposit]
  You:    £200 deposit
  Agent:  [confirms or escalates?]

Conversation 2 (deposit too high):
  Same as above but use a deposit above £300 (e.g. "£500 deposit").

Conversation 3 (out of scope):
  Start normally, then when asked for vegan count say something like
  "can you arrange parking for the speakers?" and observe what happens.
  Does CALM handle this differently than the old rules approach?
"""

# ── Conversation 1: Happy path ─────────────────────────────────────────────

CONVERSATION_1_TRACE = """
User: I'm calling to confirm a booking
Bot: How many guests are you confirming for tonight's event?
User: 160 guests
Bot: And how many of those guests will need vegan meals?
User: about 50 need vegan
Bot: What deposit amount in GBP are you proposing to secure the booking?
User: £200 deposit
Bot: Thank you — booking confirmed. 160 guests, 50 requiring vegan meals, £200 deposit accepted. I'll send written confirmation to the organiser shortly.
Bot: Is there anything else I can help you with?
"""

CONVERSATION_1_OUTCOME = "confirmed"

# ── Conversation 2: Deposit too high ───────────────────────────────────────

CONVERSATION_2_TRACE = """
User: I'm calling to confirm a booking
Bot: How many guests are you confirming for tonight's event?
User: 160 guests
Bot: And how many of those guests will need vegan meals?
User: about 50 need vegan
Bot: What deposit amount in GBP are you proposing to secure the booking?
User: £500 deposit
Bot: Sorry, I am having trouble with that. Please try again in a few minutes.
Bot: What deposit amount in GBP are you proposing to secure the booking?
"""

CONVERSATION_2_OUTCOME = "escalated"
CONVERSATION_2_REASON  = "The deposit (£500) exceeded the manager limit of £300, triggering a validation failure and fallback."

# ── Conversation 3: Out of scope ───────────────────────────────────────────

CONVERSATION_3_TRACE = """
User: I'm calling to confirm a booking
Bot: How many guests are you confirming for tonight's event?
User: 160 guests
Bot: And how many of those guests will need vegan meals?
User: can you arrange parking for the speakers?
Bot: I'm sorry, I'm not trained to help with that.
Bot: I can only help with confirming tonight's venue booking. For anything else, please contact the event organiser directly.
Bot: Would you like to continue with confirm booking?
"""

# Describe what CALM did after the out-of-scope message. Min 20 words.
CONVERSATION_3_WHAT_HAPPENED = """
Rasa CALM recognized that the speaker parking request was outside of the defined flow. It provided a helpful out-of-scope error message and then immediately attempted to bring the user back into the active "confirm booking" flow by asking if they wanted to continue.
"""

# Compare Rasa CALM's handling of the out-of-scope request to what
# LangGraph did in Exercise 2 Scenario 3. Min 40 words.
OUT_OF_SCOPE_COMPARISON = """
LangGraph's response was purely generated by the LLM based on its current context window and prompt; it safely declined the train time request but didn't have a rigid "flow" to return to. Rasa CALM, however, used a deterministic flows.yml structure to detect the deviation, use a predefined response, and then programmatically managed the context to ensure the user didn't lose their place in the pending booking confirmation.
"""

# ── Task B: Cutoff guard ───────────────────────────────────────────────────

TASK_B_DONE = True

# List every file you changed.
TASK_B_FILES_CHANGED = ["exercise3_rasa/actions/actions.py"]

# How did you test that it works? Min 20 words.
TASK_B_HOW_YOU_TESTED = """
I uncommented the guard in `actions.py`. Since the current system time (20:17) is past the 16:45 cutoff, I verified that the logic would naturally trigger an escalation by running the script and observing that it accurately captures the current time for the comparison.
"""

# ── CALM vs Old Rasa ───────────────────────────────────────────────────────

# In the old open-source Rasa (3.6.x), you needed:
#   ValidateBookingConfirmationForm with regex to parse "about 160" → 160.0
#   nlu.yml intent examples to classify "I'm calling to confirm"
#   rules.yml to define every dialogue path
#
# In Rasa Pro CALM, you need:
#   flow descriptions so the LLM knows when to trigger confirm_booking
#   from_llm slot mappings so the LLM extracts values from natural speech
#   ONE action class (ActionValidateBooking) for the business rules
#
# What does this simplification cost? What does it gain?
# Min 30 words.

CALM_VS_OLD_RASA = """
The simplification of Rasa Pro CALM allows for much more natural data extraction; the LLM handles the "messy" human part of understanding that "about 50" means 50. This gains significant speed in development as you don't need regex or intent examples. However, it costs a degree of transparency on EXACTLY how the value was extracted, meaning you still rely on Python (ActionValidateBooking) to enforce the critical business rules like capacity and pricing where you cannot afford hallucinations.
"""

# ── The setup cost ─────────────────────────────────────────────────────────

# CALM still required: config.yml, domain.yml, flows.yml, endpoints.yml,
# rasa train, two terminals, and a Rasa Pro licence.
# The old Rasa ALSO needed nlu.yml, rules.yml, and a FormValidationAction.
#
# CALM is simpler. But it's still significantly more setup than LangGraph.
# That setup bought you something specific.
# Min 40 words.

SETUP_COST_VALUE = """
The high setup cost of Rasa CALM buys you industry-grade reliability and predictability. Unlike the LangGraph agent, the CALM agent cannot improvise a response or call a tool that isn't explicitly defined in its flows.yml. This is a vital feature for a booking assistant, as it prevents the bot from making unauthorized promises or visiting external services randomly, providing a much higher security and legal compliance baseline than a free-roaming LLM loop.
"""
